# Generated by Django 5.1.1 on 2024-11-18 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_table_alter_reservation_table'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
