# Generated by Django 5.1.1 on 2024-11-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_table_location_table_table_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='admin',
        ),
    ]
