# Generated by Django 5.1.1 on 2024-11-13 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='admin',
        ),
        migrations.AddField(
            model_name='menu',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
    ]
