# Generated by Django 5.1.1 on 2024-11-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_menu_admin_menu_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
    ]
