# Generated by Django 5.1.1 on 2024-11-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menuitem_menu'),
        ('orders', '0012_alter_cart_menu_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
