# Generated by Django 5.1.1 on 2024-11-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_expected_delivery_date_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
