# Generated by Django 5.1.1 on 2024-11-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_cart_checkout_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='order_number',
        ),
    ]
