# Generated by Django 5.1.1 on 2024-11-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menuitem_menu'),
        ('orders', '0011_alter_cart_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
        ),
    ]
